Repository Requisitos-de-Software/2021.2-Tembici, pull requests merged in 2022-04, with the labels that each got.

#69 #68 - Criação do artefato EAP
  docs/assets/pos-rastreabilidade/eap/eap app.png
  docs/assets/pos-rastreabilidade/eap/eap etapas.png
  docs/pos-rastreabilidade/eap.md
  mkdocs.yml
Labels: documentation

#75 74 revisores
  docs/analise/validacao/prototipo.md
  docs/analise/validacao/validacao_informal.md
  docs/analise/verificacao/casos_de_uso.md
  docs/analise/verificacao/cenarios.md
  docs/analise/verificacao/especificacao_suplementar.md
  docs/analise/verificacao/historias_de_usuario.md
  docs/analise/verificacao/istar.md
  docs/analise/verificacao/lexicos.md
  docs/analise/verificacao/nfrframework.md
  docs/analise/verificacao/product_backlog.md
  docs/analise/verificacao/richPicture.md
  docs/assets/modelagem/persona/at.png
  docs/assets/modelagem/persona/p1.png
  docs/assets/modelagem/persona/p2.png
  docs/assets/modelagem/persona/p3.png
  docs/assets/modelagem/persona/p4.png
  docs/assets/modelagem/persona/p5.png
  docs/atas/ata_0804.md
  docs/atas/ata_1503.md
  docs/atas/ata_2303.md
  docs/atas/ata_2903.md
  docs/elicitacao/personas.md
  docs/elicitacao/priorizacao/moscow.md
  docs/elicitacao/tecnicas/brainstorm.md
  docs/elicitacao/tecnicas/introspeccao.md
  docs/elicitacao/tecnicas/questionario.md
  docs/modelagem/backlog/historias_de_usuario.md
  docs/modelagem/backlog/product_backlog.md
  docs/modelagem/casos_de_uso.md
  docs/modelagem/cenarios.md
  docs/modelagem/especificacao_suplementar.md
  docs/modelagem/istar.md
  docs/modelagem/lexicos.md
  docs/modelagem/nfrframework.md
  docs/planejamento/cronograma.md
  docs/planejamento/ferramentas.md
  docs/planejamento/heatmap.md
  docs/planejamento/metodologia.md
  docs/planejamento/politicas.md
  docs/pos-rastreabilidade/eap.md
  docs/pos-rastreabilidade/forward-from.md
  docs/pre-rastreabilidade/5w2h.md
  docs/pre-rastreabilidade/rich-picture.md
Labels: documentation, hotfix

#79 Hotfix correcoes luiz
  docs/analise/validacao/validacao_informal.md
  docs/analise/verificacao/especificacao_suplementar.md
  docs/analise/verificacao/historias_de_usuario.md
  docs/analise/verificacao/istar.md
  docs/analise/verificacao/lexicos.md
  docs/analise/verificacao/nfrframework.md
  docs/analise/verificacao/product_backlog.md
  docs/apresentacoes/apresentacao1.md
  docs/apresentacoes/apresentacao2.md
  docs/apresentacoes/apresentacao3.md
  docs/apresentacoes/apresentacao4.md
  docs/apresentacoes/apresentacao5.md
  docs/apresentacoes/apresentacao6.md
  docs/assets/planejamento/cronograma2.jpg
  docs/elicitacao/personas.md
  docs/modelagem/backlog/product_backlog.md
  docs/modelagem/casos_de_uso.md
  docs/modelagem/istar.md
  docs/modelagem/nfrframework.md
  docs/planejamento/cronograma.md
  docs/planejamento/heatmap.md
Labels: documentation, hotfix

#87 #84 - Artefato Viewpoint
  docs/analise/validacao/viewpoint.md
  mkdocs.yml
Labels: documentation

#86 #85 - Artefato corrigido
  docs/analise/verificacao/richPicture.md
  mkdocs.yml
Labels: hotfix

#93 #81 - rastreabiliade navegável
  docs/elicitacao/tecnicas/brainstorm.md
  docs/elicitacao/tecnicas/introspeccao.md
  docs/elicitacao/tecnicas/questionario.md
  docs/modelagem/casos_de_uso.md
  docs/modelagem/cenarios.md
  docs/modelagem/especificacao_suplementar.md
  docs/modelagem/lexicos.md
  docs/pos-rastreabilidade/backward-from.md
Labels: documentation
