Repository Requisitos-de-Software/2021.2-Tembici, pull requests merged in 2022-03, with the labels that each got.

#39 #33 Adição do documento de modelagem léxicos
  docs/apresentacoes/apresentacao1.md
  docs/apresentacoes/apresentacao2.md
  docs/modelagem/casos_de_uso.md
  docs/modelagem/especificacao_suplementar.md
  docs/modelagem/lexicos.md
  mkdocs.yml
Labels: documentation, enhancement

#44 37 modelagem nfr framework
  .github/issue_template.md
  docs/assets/modelagem/istar/DiagramaCadastro1.png
  docs/assets/modelagem/istar/DiagramaCadastro2.png
  docs/assets/modelagem/istar/DiagramaDevolver1.png
  docs/assets/modelagem/istar/DiagramaDevolver2.png
  docs/assets/modelagem/istar/DragramaAlugarPlano1.png
  docs/assets/modelagem/istar/DragramaAlugarPlano2.png
  docs/assets/modelagem/nfr-framework/confiabilidade/confiabilidade.jpg
  docs/assets/modelagem/nfr-framework/confiabilidade/confiabilidadeprop.jpg
  docs/assets/modelagem/nfr-framework/desempenho/desempenho.jpg
  docs/assets/modelagem/nfr-framework/desempenho/desempenhoprop.jpg
  docs/assets/modelagem/nfr-framework/rotulos/Untitled.png
  docs/assets/modelagem/nfr-framework/rotulos/Untitledn.png
  docs/assets/modelagem/nfr-framework/rotulos/parcialmentenegado.png
  docs/assets/modelagem/nfr-framework/rotulos/parcialmentesatisfeito.png
  docs/assets/modelagem/nfr-framework/suportabilidade/suportabilidade.jpg
  docs/assets/modelagem/nfr-framework/suportabilidade/suportabilidadeprop.jpg
  docs/assets/modelagem/nfr-framework/usabilidade/usabilidade.jpg
  docs/assets/modelagem/nfr-framework/usabilidade/usabilidadeprop.jpg
  docs/modelagem/especificacao_suplementar.md
  docs/modelagem/istar.md
  docs/modelagem/nfrframework.md
  docs/planejamento/cronograma.md
  mkdocs.yml
Labels: documentation, hotfix

#42 HOTFIX - Busca pelos lexicos
  docs/modelagem/lexicos.md
Labels: documentation, hotfix

#47 #46 Criaçao do product backlog
  docs/modelagem/backlog/product_backlog.md
  mkdocs.yml
Labels: documentation

#48 #46 Historias de usuário
  docs/modelagem/backlog/historias_de_usuario.md
Labels: documentation

#50 49 correções artefatos
  docs/atas/ata_1503.md
  docs/atas/ata_modelo.md
  docs/elicitacao/tecnicas/brainstorm.md
  docs/elicitacao/tecnicas/questionario.md
  docs/modelagem/lexicos.md
  docs/planejamento/cronograma.md
  mkdocs.yml
Labels: hotfix

#55 51 verificação dos casos de uso
  docs/analise/verificacao/casos_de_uso.md
  mkdocs.yml
Labels: documentation

#56 52 verificação da especificação suplementar
  docs/analise/verificacao/especificacao_suplementar.md
  docs/assets/analise/verificacao/grafico_especificacao_suplementar.png
  mkdocs.yml
Labels: documentation

#54 #53 Verificação NRF Istar
  docs/analise/verificacao/istar.md
  docs/analise/verificacao/nfrframework.md
  docs/assets/verificacao/istar/graficoIstar.png
  docs/assets/verificacao/istar/graficoNFR.png
  docs/modelagem/istar.md
  docs/modelagem/nfrframework.md
  mkdocs.yml
Labels: documentation

#64 Validação
  docs/analise/validacao/prototipo.md
  docs/analise/validacao/validacao_informal.md
  docs/assets/analise/validacao/email.png
  mkdocs.yml
Labels: documentation

#60 #58 - Verificação do documento léxicos
  docs/analise/verificacao/lexicos.md
  docs/assets/verificacao/lexicos/grafico.png
  docs/modelagem/lexicos.md
  mkdocs.yml
Labels: documentation
