Repository Requisitos-de-Software/2021.2-Tembici, pull requests merged in 2022-02, with the labels that each got.

#5 Politica de contribuicao
  docs/planejamento/planejamento.md
  docs/políticas/politicas.md
Labels: documentation

#6 #2 -Metodologias Adicionadas
  docs/planejamento.md
Labels: documentation

#23 HOTFIX - Atualização do readme para melhor identificação da equipe
  README.md
  docs/assets/foto-da-equipe/gabriel.jpeg
  docs/assets/foto-da-equipe/joao.jpeg
  docs/assets/foto-da-equipe/livia.jpeg
  docs/assets/foto-da-equipe/luiz.jpeg
  docs/assets/foto-da-equipe/paulo.jpeg
  docs/assets/foto-da-equipe/victor.jpeg
Labels: enhancement, wontfix

#26 #24 padronizacao
  docs/apresentacoes/apresentacao1.md
  docs/apresentacoes/apresentacao2.md
  docs/apresentacoes/apresentacoes.md
  docs/elicitacao/brainstorm.md
  docs/elicitacao/elicitacao.md
  docs/elicitacao/introspeccao.md
  docs/elicitacao/personas.md
  docs/elicitacao/questionario.md
  docs/pre-rastreabilidade/5w2h.md
  docs/pre-rastreabilidade/rich-picture.md
  docs/priorizacao/priorizacao.md
  mkdocs.yml
Labels: documentation, wontfix

#35 #34 Modelagem -> Especificação Suplementar
  docs/modelagem/especificacao_suplementar.md
  docs/modelo.md
  mkdocs.yml
Labels: documentation

#36 #9 - Casos de Uso
  docs/assets/modelagem/casos-de-uso/aba_ajuda.png
  docs/assets/modelagem/casos-de-uso/aba_viagem.png
  docs/assets/modelagem/casos-de-uso/cadastro.png
  docs/assets/modelagem/casos-de-uso/login.png
  docs/assets/modelagem/casos-de-uso/planos_pagamento.png
  docs/assets/modelagem/casos-de-uso/realizar_viagem.png
  docs/assets/modelagem/casos-de-uso/ver_mapa.png
  docs/modelagem/casos_de_uso.md
  mkdocs.yml
Labels: documentation
